version: '3.1'

services:
  mongodb:
    image: mongo:latest
    restart: on-failure:5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: api
    volumes:
      - mongovolume:/var/logs
    networks:
      - mongo
  mongo-express:
    image: mongo-express:latest
    restart: on-failure:5
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - mongo
  backend:
    image: 'pcbuilder.azurecr.io/back:latest'
    build:
      context: ..
      dockerfile: ./databaseVolume/backend.Dockerfile
    command: npm run dev-back
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - mongo
      - web
    restart: unless-stopped
    environment:
      HOST: 'mongodb'
      HOST_PORT: '27017'
    deploy: 
      resources: 
        limits: 
          cpus: '0.50' 
          memory: '1G' 
        reservations: 
          cpus: '0.25' 
          memory: '1G'
  web:
    image: 'pcbuilder.azurecr.io/web:latest'
    build:
      context: ..
      dockerfile: ./databaseVolume/frontend.Dockerfile
    command: npm run dev-front
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - web
    restart: unless-stopped
    environment:
      VITE_host: '20.126.235.20'
    deploy: 
      resources: 
        limits: 
          cpus: '0.50' 
          memory: '1G' 
        reservations: 
          cpus: '0.25' 
          memory: '1G'

volumes:
  mongovolume:
    driver: azure_file
    driver_opts:
      share_name: mongovolume
      storage_account_name: dbvolumes

networks:
  mongo:
    driver: bridge
  web:
    driver: bridge
